# List of all Mobu Joints
MB_JOINTS = [
    "Reference",
    "Hips",
    "LeftUpLeg",
    "LeftLeg",
    "LeftFoot",
    "LeftToeBase",
    "RightUpLeg",
    "RightLeg",
    "RightFoot",
    "RightToeBase",
    "Spine",
    "Spine1",
    "Spine2",
    "Spine3",
    "Spine4",
    "Spine5",
    "Spine6",
    "Spine7",
    "Spine8",
    "Spine9",
    "Neck",
    "Neck1",
    "Neck2",
    "Neck3",
    "Neck4",
    "Neck5",
    "Neck6",
    "Neck7",
    "Neck8",
    "Neck9",
    "Head",
    "LeftShoulder",
    "LeftArm",
    "LeftForeArm",
    "LeftHand",
    "RightShoulder",
    "RightArm",
    "RightForeArm",
    "RightHand",
    "LeftHandThumb1",
    "LeftHandThumb2",
    "LeftHandThumb3",
    "LeftHandThumb4",
    "LeftHandIndex1",
    "LeftHandIndex2",
    "LeftHandIndex3",
    "LeftHandIndex4",
    "LeftHandMiddle1",
    "LeftHandMiddle2",
    "LeftHandMiddle3",
    "LeftHandMiddle4",
    "LeftHandRing1",
    "LeftHandRing2",
    "LeftHandRing3",
    "LeftHandRing4",
    "LeftHandPinky1",
    "LeftHandPinky2",
    "LeftHandPinky3",
    "LeftHandPinky4",
    "RightHandThumb1",
    "RightHandThumb2",
    "RightHandThumb3",
    "RightHandThumb4",
    "RightHandIndex1",
    "RightHandIndex2",
    "RightHandIndex3",
    "RightHandIndex4",
    "RightHandMiddle1",
    "RightHandMiddle2",
    "RightHandMiddle3",
    "RightHandMiddle4",
    "RightHandRing1",
    "RightHandRing2",
    "RightHandRing3",
    "RightHandRing4",
    "RightHandPinky1",
    "RightHandPinky2",
    "RightHandPinky3",
    "RightHandPinky4",
]

MB_SMPL_JOINTS = {
    "Hips": ["pelvis"],
    "LeftUpLeg": ["left_hip"],
    "LeftLeg": ["left_knee"],
    "LeftFoot": ["left_ankle"],
    "LeftToeBase": ["left_toe"],
    "RightUpLeg": ["right_hip"],
    "RightLeg": ["right_knee"],
    "RightFoot": ["right_ankle"],
    "RightToeBase": ["right_toe"],
    "Spine": ["spine1"],
    "Spine1": ["spine2"],
    "Spine2": ["spine3"],
    "Spine3": ["spine4"],
    "Spine4": ["spine5"],
    "Spine5": ["spine6"],
    "Spine6": ["spine7"],
    "Spine7": ["spine8"],
    "Spine8": ["spine9"],
    "Neck": ["neck"],
    "Head": ["head"],
    "LeftShoulder": ["left_collar"],
    "LeftArm": ["left_shoulder"],
    "LeftForeArm": ["left_elbow"],
    "LeftHand": ["left_wrist"],
    "RightShoulder": ["right_collar"],
    "RightArm": ["right_shoulder"],
    "RightForeArm": ["right_elbow"],
    "RightHand": ["right_wrist"],
}