# List of all Mobu Joints
MB_JOINTS = [
    "Reference",
    "Hips",
    "LeftUpLeg",
    "LeftLeg",
    "LeftFoot",
    "LeftToeBase",
    "RightUpLeg",
    "RightLeg",
    "RightFoot",
    "RightToeBase",
    "Spine",
    "Spine1",
    "Spine2",
    "Spine3",
    "Spine4",
    "Spine5",
    "Spine6",
    "Spine7",
    "Spine8",
    "Spine9",
    "Neck",
    "Neck1",
    "Neck2",
    "Neck3",
    "Neck4",
    "Neck5",
    "Neck6",
    "Neck7",
    "Neck8",
    "Neck9",
    "Head",
    "LeftShoulder",
    "LeftArm",
    "LeftForeArm",
    "LeftHand",
    "RightShoulder",
    "RightArm",
    "RightForeArm",
    "RightHand",
    "LeftHandThumb1",
    "LeftHandThumb2",
    "LeftHandThumb3",
    "LeftHandThumb4",
    "LeftHandIndex1",
    "LeftHandIndex2",
    "LeftHandIndex3",
    "LeftHandIndex4",
    "LeftHandMiddle1",
    "LeftHandMiddle2",
    "LeftHandMiddle3",
    "LeftHandMiddle4",
    "LeftHandRing1",
    "LeftHandRing2",
    "LeftHandRing3",
    "LeftHandRing4",
    "LeftHandPinky1",
    "LeftHandPinky2",
    "LeftHandPinky3",
    "LeftHandPinky4",
    "RightHandThumb1",
    "RightHandThumb2",
    "RightHandThumb3",
    "RightHandThumb4",
    "RightHandIndex1",
    "RightHandIndex2",
    "RightHandIndex3",
    "RightHandIndex4",
    "RightHandMiddle1",
    "RightHandMiddle2",
    "RightHandMiddle3",
    "RightHandMiddle4",
    "RightHandRing1",
    "RightHandRing2",
    "RightHandRing3",
    "RightHandRing4",
    "RightHandPinky1",
    "RightHandPinky2",
    "RightHandPinky3",
    "RightHandPinky4",
]

# List of additional joints
# reference: SMPL, NSM, 100STYLE
MB_ADD_JOINTS = {
    "Hips":          ["pelvis", "Hips"],
    "LeftUpLeg":     ["left_hip", "LeftHip"],
    "LeftLeg":       ["left_knee", "LeftKnee"],
    "LeftFoot":      ["left_ankle", "LeftAnkle"],
    "LeftToeBase":   ["left_toe", "LeftToe"],
    "RightUpLeg":    ["right_hip", "RightHip"],
    "RightLeg":      ["right_knee", "RightKnee"],
    "RightFoot":     ["right_ankle", "RightAnkle"],
    "RightToeBase":  ["right_toe", "RightToe"],
    "Spine":         ["spine1", "Chest"],
    "Spine1":        ["spine2", "Chest1", "Chest2"],
    "Spine2":        ["spine3", "Chest2", "Chest3"],
    "Spine3":        ["spine4", "Chest3", "Chest4"],
    "Spine4":        ["spine5", "Chest4"],
    "Spine5":        ["spine6", "Chest5"],
    "Spine6":        ["spine7"],
    "Spine7":        ["spine8"],
    "Spine8":        ["spine9"],
    "Neck":          ["neck", "Neck"],
    "Head":          ["head", "Head"],
    "LeftShoulder":  ["left_collar", "LeftCollar"],
    "LeftArm":       ["left_shoulder", "LeftShoulder"],
    "LeftForeArm":   ["left_elbow", "LeftElbow"],
    "LeftHand":      ["left_wrist", "LeftWrist"],
    "RightShoulder": ["right_collar", "RightCollar"],
    "RightArm":      ["right_shoulder", "RightShoulder"],
    "RightForeArm":  ["right_elbow", "RightElbow"],
    "RightHand":     ["right_wrist", "RightWrist"],
}